inertial_param:
    -branch: mass
        m: 1.8
    -branch: MOI
        Jxx:
        Jxy:
        Jxz:
        Jyy:
        Jyz:
        Jzz:
    -branch: offset
        x:
        y:
        z: 0
aerodynamics_param:
    -branch: lift_coeff
        C_l:
    -branch: moment_coeff
        C_m:
length_param:
    -branch: arm_lenth
        l: 0.225