inertial_param:
    mass:
        m: 1
    MOI:
        Jxx: 1
        Jxy: 0.00000
        Jxz: 0.00000
        Jyy: 1
        Jyz: 0.00000
        Jzz: 1
    offset:
        x: 0.
        y: 0.
        z: 0.
aerodynamics_param:
    lift_coeff:
        C_l: 1
    moment_coeff:
        C_m: 1
length_param:
    arm_lenth:
        l: 0.225